//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LanguageManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LanguageManager");
		L.RegFunction("SetLanguage", SetLanguage);
		L.RegVar("Language", get_Language, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLanguage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LanguageManager.SetLanguage();
				return 0;
			}
			else if (count == 1)
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				LanguageManager.SetLanguage(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LanguageManager.SetLanguage");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Language(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, LanguageManager.Language);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

