using System.Collections.Generic;
using System;
using XLua;
using UnityEngine;
using UnityEngine.UI;
using DG.Tweening;
using TMPro;

public static class CustomSettings
{
    [LuaCallCSharp]
    public static List<Type> mymodule_lua_call_cs_list = new List<Type>()
    {
        //添加需要映射的unity原生组件
        typeof(Component),
        typeof(Transform),
        typeof(GameObject),
        typeof(Camera),
        typeof(Rigidbody),
        typeof(TrackedReference),
        typeof(Physics),
        typeof(Collider),
        typeof(Time),
        typeof(Shader),
        typeof(Renderer),
        typeof(Screen),
        typeof(CameraClearFlags),
        typeof(AudioClip),
        typeof(AssetBundle),
        typeof(ParticleSystem),
        typeof(LightType),
        typeof(SleepTimeout),
        typeof(Animator),
        typeof(KeyCode),
        typeof(Space),
        typeof(BoxCollider),
        typeof(MeshCollider),
        typeof(SphereCollider),
        typeof(CharacterController),
        typeof(CapsuleCollider),
        typeof(Animation),
        typeof(AnimationClip),
        typeof(AnimationState),
        typeof(AnimationBlendMode),
        typeof(QueueMode),
        typeof(PlayMode),
        typeof(WrapMode),
        typeof(RenderSettings),
        typeof(SkinWeights),
        typeof(RenderTexture),
        typeof(Canvas),
        typeof(CanvasScaler),
        typeof(GraphicRaycaster),
        typeof(RectTransform),
        typeof(RawImage),
        typeof(Image),
        typeof(MaskableGraphic),
        typeof(MaskableGraphic.CullStateChangedEvent),
        typeof(Button),
        typeof(Button.ButtonClickedEvent),
        typeof(ScrollRect),
        typeof(ScrollRect.ScrollRectEvent),
        typeof(Dropdown),
        typeof(Dropdown.DropdownEvent),
        typeof(Dropdown.OptionData),
        typeof(Dropdown.OptionDataList),
        typeof(Toggle),
        typeof(Toggle.ToggleEvent),
        typeof(Slider),
        typeof(Slider.SliderEvent),
        typeof(Scrollbar),
        typeof(Scrollbar.ScrollEvent),
        typeof(InputField),
        typeof(InputField.OnChangeEvent),
        typeof(InputField.SubmitEvent),
        typeof(GridLayoutGroup),
        typeof(HorizontalLayoutGroup),
        typeof(VerticalLayoutGroup),
        typeof(Mask),
        typeof(RectMask2D),
        typeof(TMP_InputField),
        typeof(TMP_InputField.OnChangeEvent),
        typeof(TMP_InputField.SubmitEvent),
        typeof(Ease),
        typeof(LoopType),
        typeof(PathType),

        //添加需要映射的自定义脚本
        typeof(Utils),
        typeof(UIButton),
        typeof(CircleRawImage),
        typeof(CircleImage),
        typeof(LoopScrollList),
        typeof(PolygonImage),
        typeof(LanguageManager),
        typeof(DebugLogTool),
        typeof(AddressablesManager),
        typeof(GameManager),
        typeof(AudioManager),
    };
}